### ISSUE TITLE
Minify output svg

### ISSUE THREAD

**Issue by wei** [amio/badgen#1]
Thanks for the project!

Is there a reason to not minify the output? 

This can be done by stripping whitespace and linebreaks after string definition to maintain readability or constructing the string from the minified svg template from the start.

**Comment by amio** [comment]
Usually the svg file would be serve with gzip compression, so a few whitespace wouldn't hurt too much(my guess, haven't measured yet), I prefer to trade this for minimal computation.

The markup has been carefully minified by hand, fortunately it's not too complicated. :D

**Comment by wei** [comment]
Right now it looks like the output contains excess lines and spaces as follows:

```

    <svg xmlns="http://www.w3.org/2000/svg" width="75.4" height="20">
      <linearGradient id="a" x2="0" y2="100%">
        <stop offset="0" stop-color="#EEE" stop-opacity=".1"/>
        <stop offset="1" stop-opacity=".1"/>
      </linearGradient>
      <mask id="m"><rect width="75.4" height="20" rx="3" fill="#FFF"/></mask>
      <g mask="url(#m)">
        <rect width="34.6" height="20" fill="#555"/>
        <rect x="34.6" width="40.8" height="20" fill="#A3E"/>
        <rect width="75.4" height="20" fill="url(#a)"/>
      </g>
      <g fill="#fff" text-anchor="start" font-family="Verdana,DejaVu Sans,sans-serif" font-size="11">
        <text x="7" y="14.8" fill="#000" opacity="0.25">chat</text>
        <text x="6" y="13.8">chat</text>
        <text x="40.1" y="14.8" fill="#000" opacity="0.25">gitter</text>
        <text x="39.1" y="13.8">gitter</text>
      </g>
    </svg>
    
```
This is understandable in the source code during string construction but I'm suggesting the output of `const svgString = badgen({subject: 'chat',status: 'gitter'})` to be as clean as possible.

imho, I think it can be cleanly formatted like either

## 1 - Minified
```
<svg xmlns="http://www.w3.org/2000/svg" width="75.4" height="20"><linearGradient id="a" x2="0" y2="100%"><stop offset="0" stop-color="#EEE" stop-opacity=".1"/><stop offset="1" stop-opacity=".1"/></linearGradient><mask id="m"><rect width="75.4" height="20" rx="3" fill="#FFF"/></mask><g mask="url(#m)"><rect width="34.6" height="20" fill="#555"/><rect x="34.6" width="40.8" height="20" fill="#A3E"/><rect width="75.4" height="20" fill="url(#a)"/></g><g fill="#fff" text-anchor="start" font-family="Verdana,DejaVu Sans,sans-serif" font-size="11"><text x="7" y="14.8" fill="#000" opacity="0.25">chat</text><text x="6" y="13.8">chat</text><text x="40.1" y="14.8" fill="#000" opacity="0.25">gitter</text><text x="39.1" y="13.8">gitter</text></g></svg>
```
or

## 2 - Beautified
```
<svg xmlns="http://www.w3.org/2000/svg" width="75.4" height="20">
  <linearGradient id="a" x2="0" y2="100%">
    <stop offset="0" stop-color="#EEE" stop-opacity=".1"/>
    <stop offset="1" stop-opacity=".1"/>
  </linearGradient>
  <mask id="m"><rect width="75.4" height="20" rx="3" fill="#FFF"/></mask>
  <g mask="url(#m)">
    <rect width="34.6" height="20" fill="#555"/>
    <rect x="34.6" width="40.8" height="20" fill="#A3E"/>
    <rect width="75.4" height="20" fill="url(#a)"/>
  </g>
  <g fill="#fff" text-anchor="start" font-family="Verdana,DejaVu Sans,sans-serif" font-size="11">
    <text x="7" y="14.8" fill="#000" opacity="0.25">chat</text>
    <text x="6" y="13.8">chat</text>
    <text x="40.1" y="14.8" fill="#000" opacity="0.25">gitter</text>
    <text x="39.1" y="13.8">gitter</text>
  </g>
</svg>
```
or both :p 

Code: [(1)](https://github.com/amio/badgen/compare/master...wei:patch-1?expand=1) or [(2)](https://github.com/amio/badgen/compare/master...wei:patch-2?expand=1)

__Gzip results I ran for fun:__

|            | Original Bytes | Gzipped Bytes |
|-----|-----|-----|
| Original | 891 | 395 |
| 1 - Minified | 746 | 373 |
| 2 - Beautified | 813 | 388 |

I'm just nit-picky about these things :p  No worries if you feel it's best left intact.

**Comment by amio** [comment]
Awesome 💪 Thanks for insights into this!

I'd like to take the (1) one, simpler regex & less bytes. Readability is not a main goal for this lib and there's a lot lot of tools could do the beautify works.
