### ISSUE TITLE
[Feature Request] Add support for icons/logos

### ISSUE THREAD

**Issue by RedSparr0w** [amio/badgen#2]
Example:
![](http://svgur.com/i/7Ef.svg)

**Comment by amio** [comment]
Nice to have, thanks!

**Comment by amio** [comment]
It's live now 🎉

[![](https://badgen.net/docker/stars/library/mongo?icon=docker&label=stars)](https://badgen.net/docker/stars/library/mongo?icon=docker&label=stars)

**Comment by RedSparr0w** [comment]
Nice work 🎉, is there a list of supported icons somewhere?

**Comment by amio** [comment]
Badgen server will auto load icon files(`.svg` or `.png` for now) from [`/icons` folder](https://github.com/amio/badgen-service/tree/master/libs/icons), once more icons added, I'll update Badgen's home page with `icon` params.

**Comment by amio** [comment]
😆docs later

[![](https://flat.badgen.net/badge/platform/ios,macos,tvos?list=1&icon=windows)](https://flat.badgen.net/badge/platform/ios,macos,tvos?list=1&icon=windows)
[![](https://flat.badgen.net/badge/chat/on%20gitter/cyan?icon=slack)](https://flat.badgen.net/badge/chat/on%20gitter/cyan?icon=slack)
