### ISSUE TITLE
Site SSL error

### ISSUE THREAD

**Issue by antonmedv** [amio/badgen#31]
Got ERR_SSL_VERSION_INTERFERENCE

**Comment by amio** [comment]
Could you describe more about the problem did you encountered? What are you trying to do?

**Comment by antonmedv** [comment]
Can't open site. Chrome error.

**Comment by antonmedv** [comment]
Yes, and all badges.

**Comment by antonmedv** [comment]
Now working ok.

**Comment by amio** [comment]
Hmm, may be a short failure from upstream provider (cloudflare or zeit?). 

@antonmedv Since it's ok now I'm closing this. Thanks for reporting, and feel free to reopen if you encounter this again.
