### ISSUE TITLE
badgen.net Website down?

### ISSUE THREAD

**Issue by cringiest** [amio/badgen#37]
![capture](https://user-images.githubusercontent.com/38025074/51874316-5e023880-2315-11e9-916e-ca3fae5d6c34.PNG)

**Comment by amio** [comment]
Yep, I guess it's related to this https://twitter.com/zeit_status/status/1089961390624755714

Created a new deployment to refresh caches, should be fine by now.

**Comment by cringiest** [comment]
Ah, thanks for the FYI.
