### ISSUE TITLE
Question: charCodeAt

### ISSUE THREAD

**Issue by styfle** [amio/badgen#5]
I noticed you have the following code in a while loop:

```js
code = text[i].charCodeAt()
```

Why did you do that instead of this?

```js
code = text.charCodeAt(i)
```

Is there a difference?

**Comment by amio** [comment]
No special opinion on this at first, while after the "emoji" support, `if (astral) text = text.match(astralRegex)` will turn it into an array, then it has to be `text[i]`.

**Comment by styfle** [comment]
I guess I thought it was odd that the index was not passed into [charCodeAt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charCodeAt)
